sudo: required
services:
  - docker

before_install:
  - docker build -t aaronrutledge/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run aaronrutledge/multi-docker npm run test -- --coverage

after_success:
  - docker build -t aaronrutledge/multi-client ./client
  - docker build -t aaronrutledge/multi-nginx ./nginx
  - docker build -t aaronrutledge/multi-server ./server
  - docker build -t aaronrutledge/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push aaronrutledge/multi-client
  - docker push aaronrutledge/multi-nginx
  - docker push aaronrutledge/multi-server
  - docker push aaronrutledge/multi-worker
