sudo: required
services:
  - docker

before_install:
  - docker build -t aaronsrutledge/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run aaronsrutledge/multi-docker npm run test -- --coverage

after_success:
  - docker build -t aaronsrutledge/multi-client ./client
  - docker build -t aaronsrutledge/multi-nginx ./nginx
  - docker build -t aaronsrutledge/multi-server ./server
  - docker build -t aaronsrutledge/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push aaronsrutledge/multi-client
  - docker push aaronsrutledge/multi-nginx
  - docker push aaronsrutledge/multi-server
  - docker push aaronsrutledge/multi-worker
